gapic_generator_version: 2.66.1
googleapis_commitish: 725496d32a359a40dd773995d3fda0342b440e15
libraries_bom_version: 26.75.0
libraries:
  - api_shortname: datastore
    name_pretty: Cloud Datastore
    product_documentation: https://cloud.google.com/datastore
    client_documentation: https://cloud.google.com/java/docs/reference/google-cloud-datastore/latest/history
    issue_tracker: https://issuetracker.google.com/savedsearches/559768
    release_level: stable
    language: java
    repo: googleapis/java-datastore
    repo_short: java-datastore
    distribution_name: com.google.cloud:google-cloud-datastore
    api_id: datastore.googleapis.com
    library_type: GAPIC_COMBO
    api_description: is a fully managed, schemaless database for\nstoring non-relational data. Cloud Datastore automatically scales with\nyour users and supports ACID transactions, high availability of reads and\nwrites, strong consistency for reads and ancestor queries, and eventual\nconsistency for all other queries.
    excluded_dependencies: grpc-google-cloud-datastore-v1
    extra_versioned_modules: datastore-v1-proto-client
    excluded_poms: grpc-google-cloud-datastore-v1
    recommended_package: com.google.cloud.datastore
    GAPICs:
      - proto_path: google/datastore/v1
      - proto_path: google/datastore/admin/v1
